# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZiKGOIIQQiOFmf4V7xrpT2ckVKhgJAW
"""
import requests
import pandas as pd
import time

from bs4 import BeautifulSoup
BASE = "https://www.bhaskar.com"
headers = {
    "User-Agent": "Mozilla/5.0"
}

import gspread
import os
import json

from google.oauth2.service_account import Credentials

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds_dict = json.loads(
    os.environ["GOOGLE_CREDS"]
)

creds = Credentials.from_service_account_info(
    creds_dict,
    scopes=SCOPES
)

client = gspread.authorize(creds)

sheet = client.open(
    "Dainik Bhaskar Dashboard"
)

def scrape_district(district):

    district_news = []

    district_url = f"https://www.bhaskar.com/local/uttar-pradesh/{district}/"

    print(f"\nScraping {district}")

    try:

        html = requests.get(
            district_url,
            headers=headers
        ).text

        soup = BeautifulSoup(
            html,
            "html.parser"
        )

        news_urls = set()

        for a in soup.find_all("a", href=True):

            href = a["href"]

            if (
                f"/local/uttar-pradesh/{district}/" in href
                and "/news/" in href
            ):

                if href.startswith("/"):
                    href = BASE + href

                news_urls.add(href)

        print(f"Found {len(news_urls)} articles")

        for url in news_urls:

            try:

                article_html = requests.get(
                    url,
                    headers=headers
                ).text

                article_soup = BeautifulSoup(
                    article_html,
                    "html.parser"
                )

                h1 = article_soup.find("h1")

                headline = (
                    h1.get_text(strip=True)
                    if h1 else ""
                )

                paragraphs = article_soup.find_all("p")

                content = " ".join(
                    p.get_text(" ", strip=True)
                    for p in paragraphs
                )

                parts = url.split("/")

                try:

                    news_index = parts.index("news")

                    if news_index == 6:
                        locality = "district"
                    else:
                        locality = parts[news_index - 1]

                except:
                    locality = "unknown"

                district_news.append({
                    "District": district.title(),
                    "Locality": locality,
                    "Headline": headline,
                    "URL": url,
                    "Content": content
                })

                time.sleep(0.1)

            except Exception as e:

                print(
                    f"Article Error: {url}"
                )

    except Exception as e:

        print(
            f"District Error: {district}"
        )

    return district_news

topic_mapping = {
    "हत्या":"Law & Order",
    "चोरी":"Law & Order",
    "पुलिस":"Law & Order",
    "बलात्कार":"Women Welfare",
    "महिला":"Women Welfare",
    "सड़क":"Infrastructure",
    "पुल":"Infrastructure",
    "अस्पताल":"Health",
    "डॉक्टर":"Health",
    "किसान":"Agriculture",
    "यूरिया":"Agriculture",
    "भाजपा":"Political",
    "सपा":"Political",
    "बसपा":"Political",
    "कांग्रेस":"Political",
    "विधायक":"Political",
    "सांसद":"Political",
    "डीएम":"Governance",
    "बिजली":"Utilities",
    "ट्रांसफार्मर":"Utilities"
}

def classify_topic(text):

    text = str(text)

    for keyword, topic in topic_mapping.items():

        if keyword in text:

            return topic

    return "Other"

def generate_summary(content):

    content = str(content)

    sentences = [
        s.strip()
        for s in content.split("।")
        if len(s.strip()) > 20
    ]

    return "। ".join(sentences[:2]) + "।"
    
seat_ws = sheet.worksheet("Seat_Mapping")

seat_mapping_df = pd.DataFrame(
    seat_ws.get_all_records()
)

seat_map = dict(
    zip(
        seat_mapping_df["Locality"].str.lower(),
        seat_mapping_df["Seat"]
    )
)

def map_seat(locality):

    return seat_map.get(
        str(locality).lower(),
        "Unknown"
    )

def upload_to_sheet(df):

    raw_ws = sheet.worksheet(
        "Raw_News"
    )

    raw_ws.clear()

    raw_ws.update(
        [df.columns.tolist()]
        +
        df.fillna("")
        .values
        .tolist()
    )

    print(
        f"Uploaded {len(df)} rows"
    )

def main():
 
    all_news = []
    districts = [
    "kushinagar",
    "deoria",
    "gorakhpur",
    "mau",
    "azamgarh",
    "ballia",
    "ghazipur",
    "maharajganj",
    "sant-kabir-nagar",
    "basti"
]

    for district in districts:

        district_news = scrape_district(district)

        all_news.extend(district_news)

    df = pd.DataFrame(all_news)
    
    if df.empty:
        print("No articles scraped")
        return
    
    df["Topic"] = (
        df["Headline"] + " " + df["Content"]
    ).apply(classify_topic)

    df["Summary"] = df["Content"].apply(
    generate_summary)

    df["Seat"] = (
        df["Locality"]
        .str.lower()
        .map(seat_map)
        .fillna("Unknown")
    )
    unmapped = (
        df[df["Seat"] == "Unknown"]
        [["District","Locality"]]
        .drop_duplicates()
    )

    unmapped_ws = sheet.worksheet(
        "Unmapped_Localities"
    )

    unmapped_ws.clear()

    if len(unmapped) > 0:

        unmapped_ws.update(
            [unmapped.columns.tolist()]
            +
            unmapped.values.tolist()
        )

    df = df[
        [
            "District",
            "Locality",
            "Seat",
            "Topic",
            "Summary",
            "Headline",
            "URL",
            "Content"
        ]
    ]

    upload_to_sheet(df)

    print(df.shape)

if __name__ == "__main__":
    main()
