# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZiKGOIIQQiOFmf4V7xrpT2ckVKhgJAW
"""

import requests

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers)

print(html.status_code)
print(html.text[:5000])

from bs4 import BeautifulSoup
import requests

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

html = requests.get(url).text

soup = BeautifulSoup(html, "html.parser")

print(soup.title.text)

for a in soup.find_all("a")[:20]:
    print(a.get("href"))

import requests
import re

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

html = requests.get(
    url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

# Look for Next.js data
print("__NEXT_DATA__" in html)

# Look for JSON-LD
print("application/ld+json" in html)

import requests
from bs4 import BeautifulSoup
import json

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

html = requests.get(
    url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

soup = BeautifulSoup(html, "html.parser")

scripts = soup.find_all(
    "script",
    type="application/ld+json"
)

print("JSON-LD Scripts Found:", len(scripts))

for i, script in enumerate(scripts[:5]):
    print("\n------------------")
    print("SCRIPT", i)
    print(script.text[:1000])

import requests
from bs4 import BeautifulSoup

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

html = requests.get(
    url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

soup = BeautifulSoup(html, "html.parser")

links = []

for a in soup.find_all("a", href=True):

    href = a["href"]

    if (
        "/news/" in href
        or "/local/" in href
    ):
        links.append(href)

print("Found:", len(links))

for i in links[:50]:
    print(i)

import requests
from bs4 import BeautifulSoup
import pandas as pd

BASE = "https://www.bhaskar.com"

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

html = requests.get(
    url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

soup = BeautifulSoup(html,"html.parser")

news_urls = set()

for a in soup.find_all("a", href=True):

    href = a["href"]

    if "/news/" in href:

        if href.startswith("/"):
            href = BASE + href

        news_urls.add(href)

print(len(news_urls))

for i in list(news_urls)[:10]:
    print(i)

import requests
from bs4 import BeautifulSoup

BASE = "https://www.bhaskar.com"

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

html = requests.get(
    url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

soup = BeautifulSoup(html, "html.parser")

news_urls = set()

for a in soup.find_all("a", href=True):

    href = a["href"]

    if (
        "/local/uttar-pradesh/kushinagar/" in href
        and "/news/" in href
    ):

        if href.startswith("/"):
            href = BASE + href

        news_urls.add(href)

print("Total Kushinagar News:", len(news_urls))

for url in list(news_urls)[:20]:
    print(url)

import requests
from bs4 import BeautifulSoup

url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/ramkola/news/ramkola-youth-dies-bengaluru-road-accident-138268457.html"

html = requests.get(
    url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

soup = BeautifulSoup(html, "html.parser")

h1 = soup.find("h1")

print("Headline:")
print(h1.text if h1 else "NOT FOUND")

paragraphs = soup.find_all("p")

print("\nParagraph Count:")
print(len(paragraphs))

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE = "https://www.bhaskar.com"

district_url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

# STEP 1: Get district page
html = requests.get(
    district_url,
    headers=headers
).text

soup = BeautifulSoup(html, "html.parser")

# STEP 2: Extract article links

news_urls = set()

for a in soup.find_all("a", href=True):

    href = a["href"]

    if (
        "/local/uttar-pradesh/kushinagar/" in href
        and "/news/" in href
    ):

        if href.startswith("/"):
            href = BASE + href

        news_urls.add(href)

print(f"Found {len(news_urls)} articles")

# STEP 3: Scrape articles

data = []

for url in news_urls:

    try:

        article_html = requests.get(
            url,
            headers=headers
        ).text

        article_soup = BeautifulSoup(
            article_html,
            "html.parser"
        )

        headline = ""

        h1 = article_soup.find("h1")

        if h1:
            headline = h1.get_text(
                strip=True
            )

        paragraphs = article_soup.find_all("p")

        content = " ".join([
            p.get_text(
                " ",
                strip=True
            )
            for p in paragraphs
        ])

        locality = url.split("/")[6]

        data.append({
            "Headline": headline,
            "Locality": locality,
            "District": "Kushinagar",
            "URL": url,
            "Content": content
        })

        print(headline)

        time.sleep(1)

    except Exception as e:

        print("Error:", url)
        print(e)

df = pd.DataFrame(data)

df.to_excel(
    "kushinagar_news.xlsx", # Changed to a local file path
    index=False
)

print(df.shape)

pip install gspread google-auth pandas

import gspread
from google.oauth2.service_account import Credentials

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_file(
    "service_account.json",   # your downloaded key file
    scopes=SCOPES
)

client = gspread.authorize(creds)

import os
print(os.listdir())

from google.colab import files

uploaded = files.upload()

import json

with open("dainik-bhaskar-dashboard-7c02c6c346a1.json") as f:
    data = json.load(f)

print(data["client_email"])

import gspread
from google.oauth2.service_account import Credentials

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_file(
    "dainik-bhaskar-dashboard-7c02c6c346a1.json",
    scopes=SCOPES
)

client = gspread.authorize(creds)

sheet = client.open(
    "Dainik Bhaskar Dashboard"
)

print(sheet.title)

df = pd.DataFrame(data)

district_url = "https://www.bhaskar.com/local/uttar-pradesh/kushinagar/"

import requests
from bs4 import BeautifulSoup

html = requests.get(
    district_url,
    headers={"User-Agent":"Mozilla/5.0"}
).text

soup = BeautifulSoup(html,"html.parser")

BASE = "https://www.bhaskar.com"

news_urls = set()

for a in soup.find_all("a", href=True):

    href = a["href"]

    if (
        "/local/uttar-pradesh/kushinagar/" in href
        and "/news/" in href
    ):

        if href.startswith("/"):
            href = BASE + href

        news_urls.add(href)

article_html = requests.get(
    url,
    headers=headers
).text

article_soup = BeautifulSoup(
    article_html,
    "html.parser"
)

print(len(news_urls))
print(list(news_urls)[:5])

import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

data = []

headers = {
    "User-Agent": "Mozilla/5.0"
}

for url in news_urls:

    try:

        article_html = requests.get(
            url,
            headers=headers
        ).text

        article_soup = BeautifulSoup(
            article_html,
            "html.parser"
        )

        # Headline
        h1 = article_soup.find("h1")

        headline = (
            h1.get_text(strip=True)
            if h1 else ""
        )

        # Content
        paragraphs = article_soup.find_all("p")

        content = " ".join(
            p.get_text(" ", strip=True)
            for p in paragraphs
        )

        # Locality extraction
        parts = url.split("/")

        try:

            news_index = parts.index("news")

            if news_index == 6:
               locality = "district"

            else:
               locality = parts[news_index - 1]

        except:

            locality = "unknown"

        data.append({
            "Headline": headline,
            "Locality": locality,
            "District": "Kushinagar",
            "URL": url,
            "Content": content
        })

        print("Done:", headline[:80])

        time.sleep(1)

    except Exception as e:

        print("Failed:", url)
        print(e)

df = pd.DataFrame(data)

print(df.shape)
df.head()

df.head()

df.columns

from datetime import datetime

today = datetime.now().strftime("%Y-%m-%d")

data.append({
    "Date": today,
    "Headline": headline,
    "Locality": locality,
    "District": "Kushinagar",
    "URL": url,
    "Content": content
})

client = gspread.authorize(creds)

sheet = client.open("Dainik Bhaskar Dashboard")

worksheet = sheet.worksheet("Raw_News")

worksheet.clear()

worksheet.update(
    [df.columns.tolist()] +
    df.values.tolist()
)

print("Uploaded Successfully")

topic_mapping = {
    "हत्या":"Law & Order",
    "चोरी":"Law & Order",
    "पुलिस":"Law & Order",
    "बलात्कार":"Women Welfare",
    "महिला":"Women Welfare",
    "सड़क":"Infrastructure",
    "पुल":"Infrastructure",
    "अस्पताल":"Health",
    "डॉक्टर":"Health",
    "किसान":"Agriculture",
    "यूरिया":"Agriculture",
    "भाजपा":"Political",
    "सपा":"Political",
    "बसपा":"Political",
    "कांग्रेस":"Political",
    "विधायक":"Political",
    "सांसद":"Political",
    "डीएम":"Governance",
    "बिजली":"Utilities",
    "ट्रांसफार्मर":"Utilities"
}

def classify_topic(text):

    for keyword, topic in topic_mapping.items():

        if keyword in text:

            return topic

    return "Other"

df["Topic"] = (
    df["Headline"] + " " + df["Content"]
).apply(classify_topic)

seat_map = dict(
    zip(
        seat_mapping_df["Locality"],
        seat_mapping_df["Seat"]
    )
)

df["Seat"] = df["Locality"].map(seat_map)

import pandas as pd

seat_ws = sheet.worksheet("Seat_Mapping")

seat_data = seat_ws.get_all_records()

seat_mapping_df = pd.DataFrame(seat_data)

print(seat_mapping_df.head())

seat_map = dict(
    zip(
        seat_mapping_df["Locality"],
        seat_mapping_df["Seat"]
    )
)

print(seat_map)

districts = [
    "kushinagar",
    "deoria",
    "gorakhpur",
    "mau",
    "azamgarh",
    "ballia",
    "ghazipur",
    "maharajganj",
    "sant-kabir-nagar",
    "basti"
]

District
Seat
Topic

districts = [
    "kushinagar",
    "deoria",
    "gorakhpur",
    "mau",
    "azamgarh",
    "ballia",
    "ghazipur",
    "maharajganj",
    "sant-kabir-nagar",
    "basti"
]

base_url = "https://www.bhaskar.com/local/uttar-pradesh/{}/"

all_news = []

for district in districts:

    district_url = base_url.format(district)

    print(f"Scraping {district}")

    try:

        html = requests.get(
            district_url,
            headers=headers
        ).text

        soup = BeautifulSoup(
            html,
            "html.parser"
        )

        news_urls = set()

        for a in soup.find_all("a", href=True):

            href = a["href"]

            if (
                f"/local/uttar-pradesh/{district}/" in href
                and "/news/" in href
            ):

                if href.startswith("/"):
                    href = BASE + href

                news_urls.add(href)

        print(
            district,
            len(news_urls)
        )

    except Exception as e:

        print(
            district,
            e
        )
for url in news_urls:

    try:

        article_html = requests.get(
            url,
            headers=headers
        ).text

        article_soup = BeautifulSoup(
            article_html,
            "html.parser"
        )

        h1 = article_soup.find("h1")

        headline = (
            h1.get_text(strip=True)
            if h1 else ""
        )

        paragraphs = article_soup.find_all("p")

        content = " ".join(
            p.get_text(" ", strip=True)
            for p in paragraphs
        )

        all_news.append({
            "District": district,
            "Headline": headline,
            "URL": url,
            "Content": content
        })

    except:
        pass

for url in news_urls:

    try:

        article_html = requests.get(
            url,
            headers=headers
        ).text

        article_soup = BeautifulSoup(
            article_html,
            "html.parser"
        )

        h1 = article_soup.find("h1")

        headline = (
            h1.get_text(strip=True)
            if h1 else ""
        )

        paragraphs = article_soup.find_all("p")

        content = " ".join(
            p.get_text(" ", strip=True)
            for p in paragraphs
        )

        all_news.append({
            "District": district,
            "Headline": headline,
            "URL": url,
            "Content": content
        })

    except:
        pass

seat_ws = sheet.worksheet("Seat_Mapping")

seat_mapping_df = pd.DataFrame(
    seat_ws.get_all_records()
)

seat_map = dict(
    zip(
        seat_mapping_df["Locality"].str.lower(),
        seat_mapping_df["Seat"]
    )
)

df["Seat"] = (
    df["Locality"]
    .str.lower()
    .map(seat_map)
)

sheet = client.open("Dainik Bhaskar Dashboard")

worksheet = sheet.worksheet("Raw_News")

worksheet.clear()

worksheet.update(
    [df.columns.tolist()] +
    df.values.tolist()
)

print("Uploaded Successfully")

print(df["District"].value_counts())

for district in districts:
    print(district)

print(f"\nDistrict: {district}")
print(f"URLs Found: {len(news_urls)}")

#Main Scrapper Code
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE = "https://www.bhaskar.com"

headers = {
    "User-Agent": "Mozilla/5.0"
}

districts = [
    "kushinagar",
    "deoria",
    "gorakhpur",
    "mau",
    "azamgarh",
    "ballia",
    "ghazipur",
    "maharajganj",
    "sant-kabir-nagar",
    "basti"
]

base_url = "https://www.bhaskar.com/local/uttar-pradesh/{}/"

all_news = []

for district in districts:

    district_url = base_url.format(district)

    print(f"\n========== {district.upper()} ==========")

    try:

        html = requests.get(
            district_url,
            headers=headers
        ).text

        soup = BeautifulSoup(
            html,
            "html.parser"
        )

        news_urls = set()

        for a in soup.find_all("a", href=True):

            href = a["href"]

            if (
                f"/local/uttar-pradesh/{district}/" in href
                and "/news/" in href
            ):

                if href.startswith("/"):
                    href = BASE + href

                news_urls.add(href)

        print(f"Articles Found: {len(news_urls)}")

        for url in news_urls:

            try:

                article_html = requests.get(
                    url,
                    headers=headers
                ).text

                article_soup = BeautifulSoup(
                    article_html,
                    "html.parser"
                )

                # Headline
                h1 = article_soup.find("h1")

                headline = (
                    h1.get_text(strip=True)
                    if h1 else ""
                )

                # Content
                paragraphs = article_soup.find_all("p")

                content = " ".join(
                    p.get_text(" ", strip=True)
                    for p in paragraphs
                )

                # Locality extraction
                parts = url.split("/")

                try:

                    news_index = parts.index("news")

                    if news_index == 6:
                        locality = "district"

                    else:
                        locality = parts[news_index - 1]

                except:
                    locality = "unknown"

                all_news.append({
                    "District": district.title(),
                    "Locality": locality,
                    "Headline": headline,
                    "URL": url,
                    "Content": content
                })

                print(f"✓ {headline[:60]}")

                # Prevent rate limiting
                time.sleep(1)

            except Exception as e:

                print(f"Article Error: {url}")
                print(e)

    except Exception as e:

        print(f"District Error: {district}")
        print(e)

# Create DataFrame
df = pd.DataFrame(all_news)

print("\n====================")
print("DISTRICT COUNTS")
print("====================")
print(df["District"].value_counts())

print("\nTotal Articles:", len(df))

#optional
print(df["District"].value_counts())

#Topic Mapping Step
topic_mapping = {

    "हत्या":"Law & Order",
    "अपराध":"Law & Order",
    "गिरफ्तार":"Law & Order",
    "पुलिस":"Law & Order",

    "महिला":"Women Welfare",
    "बालिका":"Women Welfare",
    "दुष्कर्म":"Women Welfare",

    "भाजपा":"Political",
    "सपा":"Political",
    "बसपा":"Political",
    "कांग्रेस":"Political",
    "विधायक":"Political",
    "सांसद":"Political",

    "डीएम":"Governance",
    "एसडीएम":"Governance",
    "प्रशासन":"Governance",

    "सड़क":"Infrastructure",
    "पुल":"Infrastructure",
    "निर्माण":"Infrastructure",

    "अस्पताल":"Health",
    "डॉक्टर":"Health",
    "स्वास्थ्य":"Health",

    "किसान":"Agriculture",
    "यूरिया":"Agriculture",
    "फसल":"Agriculture",

    "बिजली":"Utilities",
    "ट्रांसफार्मर":"Utilities",

    "विद्यालय":"Education",
    "स्कूल":"Education",
    "कॉलेज":"Education",

    "मंदिर":"Religious/Social",
    "मोहर्रम":"Religious/Social",
    "भंडारा":"Religious/Social"
}

def classify_topic(text):

    text = str(text)

    for keyword, topic in topic_mapping.items():

        if keyword in text:
            return topic

    return "Other"

df["Topic"] = (
    df["Headline"].fillna("") +
    " " +
    df["Content"].fillna("")
).apply(classify_topic)

#optional
print(df.columns)

#optional
print(df["Topic"].value_counts())

# Mapping 'Localities' to their corresponding 'Seats'
seat_ws = sheet.worksheet("Seat_Mapping")

seat_mapping_df = pd.DataFrame(
    seat_ws.get_all_records()
)

seat_map = dict(
    zip(
        seat_mapping_df["Locality"].str.lower(),
        seat_mapping_df["Seat"]
    )
)

df["Seat"] = (
    df["Locality"]
    .astype(str)
    .str.lower()
    .map(seat_map)
)

#optional
df[["District","Locality","Seat"]].head(20)

#optional
seat_ws = sheet.worksheet("Seat_Mapping")

seat_mapping_df = pd.DataFrame(
    seat_ws.get_all_records()
)

seat_map = dict(
    zip(
        seat_mapping_df["Locality"].str.lower(),
        seat_mapping_df["Seat"]
    )
)

df["Seat"] = (
    df["Locality"]
    .astype(str)
    .str.lower()
    .map(seat_map)
)

#optional
print(
    df[df["Seat"].isna()]
    ["Locality"]
    .value_counts()
)

#optional
print(df["District"].value_counts())

#for finding out unmapped localities
unmapped = (
    df[df["Seat"].isna()]
    [["District","Locality"]]
    .drop_duplicates()
)

unmapped_ws = sheet.worksheet("Unmapped_Localities")

unmapped_ws.clear()

unmapped_ws.update(
    [unmapped.columns.tolist()] +
    unmapped.values.tolist()
)

#important to fill out columns in raw data
df = df[[
    "District",
    "Locality",
    "Seat",
    "Topic",
    "Headline",
    "URL",
    "Content"
]]

#Uploading data to excel
raw_ws = sheet.worksheet("Raw_News")

raw_ws.clear()

raw_ws.update(
    [df.columns.tolist()] +
    df.fillna("").values.tolist()
)

def scrape_district(district):

    district_news = []

    district_url = f"https://www.bhaskar.com/local/uttar-pradesh/{district}/"

    print(f"\nScraping {district}")

    try:

        html = requests.get(
            district_url,
            headers=headers
        ).text

        soup = BeautifulSoup(
            html,
            "html.parser"
        )

        news_urls = set()

        for a in soup.find_all("a", href=True):

            href = a["href"]

            if (
                f"/local/uttar-pradesh/" in href
                and "/news/" in href
            ):

                if href.startswith("/"):
                    href = BASE + href

                news_urls.add(href)

        print(f"Found {len(news_urls)} articles")

        for url in news_urls:

            try:

                article_html = requests.get(
                    url,
                    headers=headers
                ).text

                article_soup = BeautifulSoup(
                    article_html,
                    "html.parser"
                )

                h1 = article_soup.find("h1")

                headline = (
                    h1.get_text(strip=True)
                    if h1 else ""
                )

                paragraphs = article_soup.find_all("p")

                content = " ".join(
                    p.get_text(" ", strip=True)
                    for p in paragraphs
                )

                parts = url.split("/")

                try:

                    news_index = parts.index("news")

                    if news_index == 6:
                        locality = "district"
                    else:
                        locality = parts[news_index - 1]

                except:
                    locality = "unknown"

                district_news.append({
                    "District": district.title(),
                    "Locality": locality,
                    "Headline": headline,
                    "URL": url,
                    "Content": content
                })

                time.sleep(0.25)

            except Exception as e:

                print(
                    f"Article Error: {url}"
                )

    except Exception as e:

        print(
            f"District Error: {district}"
        )

    return district_news

def classify_topic(text):

    text = str(text)

    for keyword, topic in topic_mapping.items():

        if keyword in text:

            return topic

    return "Other"

def map_seat(locality):

    return seat_map.get(
        str(locality).lower(),
        "Unknown"
    )

def upload_to_sheet(df):

    raw_ws = sheet.worksheet(
        "Raw_News"
    )

    raw_ws.clear()

    raw_ws.update(
        [df.columns.tolist()]
        +
        df.fillna("")
        .values
        .tolist()
    )

    print(
        f"Uploaded {len(df)} rows"
    )

def main():

    all_news = []
    districts = [
    "kushinagar",
    "deoria",
    "gorakhpur",
    "mau",
    "azamgarh",
    "ballia",
    "ghazipur",
    "maharajganj",
    "sant-kabir-nagar",
    "basti"
]

    for district in districts:

        district_news = scrape_district(district)

        all_news.extend(district_news)

    df = pd.DataFrame(all_news)

    df["Topic"] = (
        df["Headline"] + " " + df["Content"]
    ).apply(classify_topic)

    df["Seat"] = (
        df["Locality"]
        .str.lower()
        .map(seat_map)
        .fillna("Unknown")
    )

    upload_to_sheet(df)

    print(df.shape)

if __name__ == "__main__":
    main()