name: Daily Bhaskar Scraper

on:

  schedule:
    - cron: '30 1 * * *'

  workflow_dispatch:

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          python scraper.py
